spring.application.name=kushipg6

spring.datasource.url=jdbc:postgresql://localhost:5432/kushipg6
spring.datasource.username=postgres
spring.datasource.password=Admin@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.default-property-inclusion=non_null
spring.jpa.open-in-view=false

server.port=8080

cloudinary.cloud-name=delzppl5n
cloudinary.api-key=657456984165565
cloudinary.api-secret=W5mF9_TiAs9SOcnxDtjNK4HlPq8