spring.application.name=kushipg6

spring.datasource.url=jdbc:postgresql://localhost:5432/kushipg6
spring.datasource.username=postgres
spring.datasource.password=Admin@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080